import os
import sys

def fix():
    try:
        import django
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'psicosystem.settings')
        django.setup()
        from django.db import connection
        cursor = connection.cursor()
        
        # Ensure NotaClinica table exists
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "P2_Gestion_Clinica_notaclinica" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "contenido" text NOT NULL,
                "fecha" timestamp with time zone NOT NULL,
                "expediente_id" bigint NOT NULL,
                "psicologo_id" integer NULL
            );
        """)
        print("NotaClinica ensured.")
        
        # Ensure ArchivoAdjunto table exists
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "P2_Gestion_Clinica_archivoadjunto" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "archivo" varchar(100) NOT NULL,
                "descripcion" varchar(255) NOT NULL,
                "fecha_subida" timestamp with time zone NOT NULL,
                "expediente_id" bigint NOT NULL,
                "subido_por_id" integer NULL
            );
        """)
        print("ArchivoAdjunto ensured.")

        # Fix django_migrations
        cursor.execute("DELETE FROM django_migrations WHERE app='P2_Gestion_Clinica' AND name IN ('0008_notaclinica_archivoadjunto', '0009_remove_evolucion_cita_remove_evolucion_paciente_and_more');")
        cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES ('P2_Gestion_Clinica', '0008_notaclinica_archivoadjunto', NOW());")
        cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES ('P2_Gestion_Clinica', '0009_remove_evolucion_cita_remove_evolucion_paciente_and_more', NOW());")
        print("django_migrations fixed.")
    except Exception as e:
        print("ERROR in fix_db:", e)

if __name__ == '__main__':
    fix()
