# Generated by Django 6.0.3 on 2026-06-23 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0013_merge_20260622_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_fecha_pass',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
