# Generated by Django 6.0.3 on 2026-06-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0009_remove_evolucion_cita_remove_evolucion_paciente_and_more'),
        ('P4_IA_Administracion', '0004_merge_20260622_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='pdf_archivo',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_path',
            field=models.FileField(blank=True, null=True, upload_to='finanzas/comprobantes/'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('PAGO', 'Pago de Sesión'), ('DEUDA', 'Cargo de Sesión'), ('AJUSTE', 'Ajuste de Saldo')], default='PAGO', max_length=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='transaccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='P4_IA_Administracion.transaccion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='P2_Gestion_Clinica.paciente'),
        ),
        migrations.DeleteModel(
            name='DiagnosticoIA',
        ),
    ]
