# Generated by Django 6.0.3 on 2026-06-23 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0008_notaclinica_archivoadjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolucion',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='expedienteclinico',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DiagnosticoPaciente',
        ),
        migrations.DeleteModel(
            name='Evolucion',
        ),
        migrations.DeleteModel(
            name='ExpedienteClinico',
        ),
    ]
