# Generated by Django 6.0.3 on 2026-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0007_merge_20260622_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.IntegerField(default=60),
        ),
    ]
